### ISSUE TITLE
Circular dependecy between Test::META and License::SPDX

### ISSUE THREAD

**Issue by frithnanth** [jonathanstowe/License-SPDX#3]
In this module there's a test, t/001-meta.t in which I see these lines:
```raku
BEGIN {
    require Test::META <&meta-ok>;
```
but Test::META is not listed as a dependency in the META6.json file.
OTOH Test::META lists this module in the `depends` section of its META6.json file, so the only way to install those modules is to `zef install --/test` one of them.

**Comment by jonathanstowe** [comment]
Not stating the Test::META as a dependency is intentional (testing the meta on installation is largely redundant as it wouldn't have got that far if it wasn't a good META6.json,) however yes this is a cockup and will need to be removed (I tend to just put the meta test without even thinking about it.)

**Comment by jonathanstowe** [comment]
Cheers! I'll be making a release with v3.11.1 in a bit.
